In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.dirname(os.getcwd())))

from src import utils

In [3]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [4]:
print(utils.subarray_2D(array, 0, 0, 3))

[[0 0 0]
 [0 1 2]
 [0 4 5]]


In [5]:
print(utils.subarray_2D(array, 1, 1, 5))

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 1 2 3 0]]
